//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DXApplication2.Module.BusinessObjects.ORMDataModel1
{

    [DefaultProperty("Sogiolam")]
    public partial class Bangluong : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Nhanvien fNhanvienID;
        [Association(@"BangluongReferencesNhanvien")]
        [DevExpress.Xpo.DisplayName(@"ID Nhân viên")]
        public Nhanvien NhanvienID
        {
            get { return fNhanvienID; }
            set { SetPropertyValue<Nhanvien>(nameof(NhanvienID), ref fNhanvienID, value); }
        }
        short fNam;
        [DevExpress.Xpo.DisplayName(@"Năm")]
        public short Nam
        {
            get { return fNam; }
            set { SetPropertyValue<short>(nameof(Nam), ref fNam, value); }
        }
        short fThang;
        [DevExpress.Xpo.DisplayName(@"Tháng")]
        public short Thang
        {
            get { return fThang; }
            set { SetPropertyValue<short>(nameof(Thang), ref fThang, value); }
        }
        decimal fSogiolam;
        [DevExpress.Xpo.DisplayName(@"Số giờ làm")]
        public decimal Sogiolam
        {
            get { return fSogiolam; }
            set { SetPropertyValue<decimal>(nameof(Sogiolam), ref fSogiolam, value); }
        }
        decimal fLuong;
        [DevExpress.Xpo.DisplayName(@"Lương")]
        public decimal Luong
        {
            get { return fLuong; }
            set { SetPropertyValue<decimal>(nameof(Luong), ref fLuong, value); }
        }
    }

}
