//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DXApplication2.Module.BusinessObjects.ORMDataModel1
{

    [DefaultProperty("Soluong")]
    public partial class Dinhluong : XPObject
    {
        SanPham fSanphamID;
        [Association(@"DinhluongReferencesSanPham")]
        [DevExpress.Xpo.DisplayName(@"ID Sản phẩm")]
        public SanPham SanphamID
        {
            get { return fSanphamID; }
            set { SetPropertyValue<SanPham>(nameof(SanphamID), ref fSanphamID, value); }
        }
        SanPham fThanhphanID;
        public SanPham ThanhphanID
        {
            get { return fThanhphanID; }
            set { SetPropertyValue<SanPham>(nameof(ThanhphanID), ref fThanhphanID, value); }
        }
        short fSoluong;
        public short Soluong
        {
            get { return fSoluong; }
            set { SetPropertyValue<short>(nameof(Soluong), ref fSoluong, value); }
        }
    }

}
