//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DXApplication2.Module.BusinessObjects.ORMDataModel1
{

    [DefaultProperty("Soluong")]
    public partial class Dongnhap : DevExpress.Persistent.BaseImpl.BaseObject
    {
        SanPham fSanPhamID;
        [Association(@"DongnhapReferencesSanPham")]
        [DevExpress.Xpo.DisplayName(@"ID Sản phẩm")]
        public SanPham SanPhamID
        {
            get { return fSanPhamID; }
            set { SetPropertyValue<SanPham>(nameof(SanPhamID), ref fSanPhamID, value); }
        }
        Phieunhap fNhapID;
        [Association(@"DongnhapReferencesPhieunhap")]
        [DevExpress.Xpo.DisplayName(@"ID Nhập")]
        public Phieunhap NhapID
        {
            get { return fNhapID; }
            set { SetPropertyValue<Phieunhap>(nameof(NhapID), ref fNhapID, value); }
        }
        short fSoluong;
        [DevExpress.Xpo.DisplayName(@"Số lượng")]
        public short Soluong
        {
            get { return fSoluong; }
            set { SetPropertyValue<short>(nameof(Soluong), ref fSoluong, value); }
        }
        decimal fDongia;
        [DevExpress.Xpo.DisplayName(@"Đơn giá")]
        public decimal Dongia
        {
            get { return fDongia; }
            set { SetPropertyValue<decimal>(nameof(Dongia), ref fDongia, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Thành tiền")]
        [PersistentAlias("ToDecimal([Soluong]) * [Dongia]")]
        public string Thanhtien
        {
            get { return (string)(EvaluateAlias(nameof(Thanhtien))); }
        }
    }

}
