//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DXApplication2.Module.BusinessObjects.ORMDataModel1
{

    [DefaultProperty("HoadonCT")]
    public partial class HoadonCT : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Hoadon fHoadonID;
        [Association(@"HoadonCTReferencesHoadon")]
        [DevExpress.Xpo.DisplayName(@"Hoá đơn ID")]
        public Hoadon HoadonID
        {
            get { return fHoadonID; }
            set { SetPropertyValue<Hoadon>(nameof(HoadonID), ref fHoadonID, value); }
        }
        SanPham fSanphamID;
        [Association(@"HoadonCTReferencesSanPham")]
        [DevExpress.Xpo.DisplayName(@"Sản phẩm ID")]
        public SanPham SanphamID
        {
            get { return fSanphamID; }
            set { SetPropertyValue<SanPham>(nameof(SanphamID), ref fSanphamID, value); }
        }
        double fSoluong;
        [DevExpress.Xpo.DisplayName(@"Số lượng")]
        public double Soluong
        {
            get { return fSoluong; }
            set { SetPropertyValue<double>(nameof(Soluong), ref fSoluong, value); }
        }
        decimal fDongia;
        [DevExpress.Xpo.DisplayName(@"Đơn giá")]
        public decimal Dongia
        {
            get { return fDongia; }
            set { SetPropertyValue<decimal>(nameof(Dongia), ref fDongia, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Thành tiền")]
        [PersistentAlias("ToDecimal([Soluong]) * [Dongia]")]
        public string Thanhtien
        {
            get { return (string)(EvaluateAlias(nameof(Thanhtien))); }
        }
        [Association(@"TieuhaoReferencesHoadonCT"), Aggregated]
        public XPCollection<Tieuhao> Tieuhaos { get { return GetCollection<Tieuhao>(nameof(Tieuhaos)); } }
    }

}
