//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DXApplication2.Module.BusinessObjects.ORMDataModel1
{

    [DefaultProperty("SanPhamID")]
    public partial class Tieuhao : DevExpress.Persistent.BaseImpl.BaseObject
    {
        SanPham fSanphamID;
        [Association(@"TieuhaoReferencesSanPham")]
        [DevExpress.Xpo.DisplayName(@"ID Sản phẩm")]
        public SanPham SanphamID
        {
            get { return fSanphamID; }
            set { SetPropertyValue<SanPham>(nameof(SanphamID), ref fSanphamID, value); }
        }
        HoadonCT fHoadonCTID;
        [Association(@"TieuhaoReferencesHoadonCT")]
        [DevExpress.Xpo.DisplayName(@"ID Hoá đơn CT")]
        public HoadonCT HoadonCTID
        {
            get { return fHoadonCTID; }
            set { SetPropertyValue<HoadonCT>(nameof(HoadonCTID), ref fHoadonCTID, value); }
        }
        int fSoluong;
        [DevExpress.Xpo.DisplayName(@"Số lượng")]
        public int Soluong
        {
            get { return fSoluong; }
            set { SetPropertyValue<int>(nameof(Soluong), ref fSoluong, value); }
        }
        string fDongiaVon;
        [DevExpress.Xpo.DisplayName(@"Đơn giá vốn")]
        public string DongiaVon
        {
            get { return fDongiaVon; }
            set { SetPropertyValue<string>(nameof(DongiaVon), ref fDongiaVon, value); }
        }
    }

}
